obstacle_range: 2.5
raytrace_range: 5.0 #3.0
footprint: [[0.22, -0.17], [0.22, 0.15], [-0.22, 0.15], [-0.22, -0.17]]
footprint_inflation: 0.3 #0.01
#robot_radius: 0.2
#inflation_radius: 0.2 #0.1
max_obstacle_height: 0.6
min_obstacle_height: 0.0
#observation_sources: scan
#scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
#point_cloud_sensor: {data_type: PointCloud2, topic: /camera/depth/color/points, marking: true, clearing: true}  

lidar_layer:
    observation_sources: base_scan
    base_scan: {data_type: LaserScan,
                topic: /scan_f,
                expected_update_rate: 0.4,
                marking: true,
                clearing: true
                #max_obstacle_height: 0.4,
                #min_obstacle_height: 0.08
                }

sonar_layer:
  enabled:            true
  clear_threshold:    0.25
  mark_threshold:     0.50
  topics: ["/xcar/sonar1", "/xcar/sonar2"]   
  clear_on_max_reading: true
