controller_frequency: 3.0  #向机器人底盘发送的控制速度的频率
controller_patience: 5.0   #等待控制速度的时间间隔，如果控制速度的发布超过设置时间，则认为局部路径规划失败
 
planner_frequency: 1.0     #全局规划器的执行频率，如果为0则只有出现新的目标点，才会重新规划
planner_patience: 5.0      #进行全局规划的时间间隔，如果超时则认为规划失败

recovery_behavior_enabled: true #是否使用恢复模块，默认值为true
clearing_rotation_allowed: true #是否允许旋转恢复行为，默认为true

# base_global_planner: "global_planner/GlobalPlanner"      #全局地图参数配置
base_local_planner: "dwa_local_planner/DWAPlannerROS"    #局部地图参数配置

DWAPlannerROS:

# Robot Configuration Parameters - stdr robot

#  acc_lim_x: 0.3        #机器人在x方向的极限加速度，单位为 meters/sec^2
#  acc_lim_y: 0.0        # 机器人在y方向的极限加速度，单位为 meters/sec^2
  acc_lim_th: 0.1       #器人的极限旋转加速度，单位为 rad/sec^2

  max_trans_vel: 0.2    #机器人最大平移速度的绝对值，单位为 m/s
  min_trans_vel: 0.05   #机器人最小平移速度的绝对值，单位为 m/s，如果为负值表示可以后退.
  trans_stopped_vel: 0.1   #机器人被认属于“停止”状态时的平移速度，如果机器人的速度低于该值，则认为机器人已停止，单位:米/秒
 
  max_vel_x: 0.18    #x方向最大线速度绝对值，单位:米/秒
  min_vel_x: -0.1   #x方向最小线速度绝对值，单位:米/秒，如果为负值表示可以后退.
  max_vel_y: 0.0    #y方向最大线速度绝对值，单位:米/秒，当不允许横向移动则设置为0
  min_vel_y: 0.0    #y方向最小线速度绝对值，单位:米/秒，当不允许横向移动则设置为0

 
#  max_rot_vel: 3    #机器人的最大旋转角速度的绝对值，单位为 rad/s，0.1 rad = 5.7 degree
#  min_rot_vel: 0.1    #机器人的最小旋转角速度的绝对值，单位为 rad/s，0.1 rad = 5.7 degree
#  rot_stopped_vel: 0.4 #机器人被认属于“停止”状态时的旋转速度。单位为 rad/s，0.1 rad = 5.7 degree

# Goal Tolerance Parameters 目标距离公差参数
  yaw_goal_tolerance: 0.5  #到达目标点时偏行角允许的误差，单位:rad，0.1 rad = 5.7 degree
  xy_goal_tolerance: 0.2   #到达目标点时,在xy平面内与目标点的距离误差，单位:米
  latch_xy_goal_tolerance: true  #设置为true时表示：如果到达容错距离内,机器人就会原地旋转；即使转动是会跑出容错距离外。

 

# Forward Simulation Parameters

#  sim_time: 5.0    # 1.7

#  sim_granularity: 0.05 #0.025

#  vx_samples: 10 #10    # default 3

#  vy_samples: 1    # diff drive robot, there is only one sample

#  vth_samples: 20  # 20

#  controller_frequency:  3 

#  use_dwa: true 

# Trajectory Scoring Parameters

#  path_distance_bias: 32 #90.0      # 32.0

#  goal_distance_bias: 24.0      # 24.0

#  occdist_scale: 0.6            # 0.01

#  forward_point_distance: 0.5 #0.325 # 0.325

#  stop_time_buffer: 1 #0.5         # 0.2

#  scaling_speed: 0.1 #0.20           # 0.25

#  max_scaling_factor: 0.2       # 0.2

#  publish_cost_grid: true # false

 

# Oscillation Prevention Parameters

  oscillation_reset_dist: 0.3  #机器人必须运动多少米远后才能复位震荡标记（default 0.05）
  oscillation_timeout: 3
 

# Global Plan Parameters

#  prune_plan: false
