local_costmap:
   global_frame: odom #map
   robot_base_frame: base_link #base_footprint
   update_frequency: 3.0
   publish_frequency: 3.0
   static_map: false #true
   rolling_window:  true
   width: 6.0
   height: 6.0
   resolution: 0.02
   transform_tolerance: 1.0
   inflation_radius: 0.20
#   observation_sources: sonar
#   scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
#   sonar: {data_type: Range, topic: /xcar/sonar1, marking: true, clearing: true}

   plugins:
     - {name: lidar_layer, type: "costmap_2d::VoxelLayer"}
     #- {name: sonar_layer,   type: "range_sensor_layer::RangeSensorLayer"}
     - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
 
  #Configuration for the sensors that the costmap will use to update a map   
