base_link: 'base_link'
# ====================================================
gripper:
    end_effector_name: gripper  #ee group name
    end_effector_parent_link: tool0
    #actuated joints in end effector
    joints : []

    #open position
    pregrasp_posture : [0.0, 0.0]
    pregrasp_time_from_start : 4.0

    #close position
    grasp_posture : [0.0, 0.0]
    grasp_time_from_start : 4.0
    #???
    #desired pose from end effector to grasp - [x,y,z]
    grasp_pose_to_eef : [0.06, 0, 0]     #这里的0.06决定生成姿态的圆心范围

    #desired pose from end effector to grasp - [r, p, y]
    grasp_pose_to_eef_rotation : [0, 0, 0]  # 1.5707 = PI/2
    #根据自己moveit_config文件夹中的srdf进行设置
    
